# User Role
CUSTOMER_ADMIN_ROLE     = 1
CUSTOMER_DEVELOPER_ROLE = 2
CUSTOMER_TESTER_ROLE    = 3
CUSTOMER_OPERATION_ROLE = 4
CUSTOMER_GENERAL_ROLE   = 5

# App status
APP_PROCESSING      = 0
APP_COMPLETED       = 1
APP_TESTING         = 2
APP_TEST_COMPLETED  = 3
APP_RELEASED        = 4

# Data mode
SANDBOX    = 0
PRODUCTION = 1

PER_PAGES = [20, 40, 60]
MIN_PER_PAGE = 20

# Item mode
UPDATE = 1
VIEW   = 2
HIDDEN = 3

# Unit position
PREFIX_POSITION = 1
SUFFIX_POSITION = 2

# Item type
TEXT          = 1
CHECKBOX      = 2
SELECTION     = 3
DATE          = 4
TIME          = 5
NUMBER        = 6
RADIO         = 7
URL           = 8
ATTACHMENT    = 9
LOOKUP        = 10
CREATED_TIME  = 11
LAST_MODIFIED_TIME = 12
LABEL  = 13
BUTTON = 14
LIST_OBJECT = 15
IFRAME = 16

# Paginator
APPS_LIMIT_VIEW = 15


# Mode app
ENTRY_FORM = 1
LIST_VIEW  = 2
MENU = 3

# Delete flag
DELETE_FLAG_ENABLE = 0
DELETE_FLAG_DISABLE = 1

# Event list
RECORD_SEARCH = 1
DISPLAY_CONTENT = 2
ACTION_ON_OTHER_OBJECTS = 3
RECORD_REGISTER = 4
DELETE_RECORD = 5
SCREEN_TRANSITION = 6
SET_OUTPUT = 7
SUM = 8
MULTIPLICATION = 9
RESET = 10
SCREEN_DISPLAY = 11